---

- block:
    - name: check if sysmon archive is present
      win_stat:
        path: "{{ win_temp_dir }}\\{{ win_sysmon_url | basename }}"
      register: sysmondl
    - name: download sysmon
      win_get_url:
        url: "{{ win_sysmon_url }}"
        dest: "{{ win_temp_dir }}\\{{ win_sysmon_url | basename }}"
      when: not sysmondl.stat.exists
    - name: unzip sysmon
      win_unzip:
        src: "{{ win_temp_dir }}\\{{ win_sysmon_url | basename }}"
        dest: "{{ win_temp_dir }}\\sysmon"
        creates: "{{ win_temp_dir }}\\sysmon\\sysmon.exe"
    - name: Set sysmon file path
      ansible.builtin.set_fact:
        sysmon_path: "{{ win_temp_dir }}\\sysmon\\sysmon64"
  when: win_sysmon_direct|bool

- block:
    - name: install sysmon with chocolatey
      win_chocolatey:
        name: sysmon
        state: present
        ignore_checksums: yes
        ## FIXME!
        # install_args: "--checksum {{ win_sysmon_sha256 }}"
    - name: Set sysmon file path
      ansible.builtin.set_fact:
        sysmon_path: "c:\\ProgramData\\chocolatey\\lib\\sysmon\\tools\\sysmon64"
  when: not win_sysmon_direct|bool

- block:
    - name: Copy Sysmon template
      win_template:
        src: "{{ win_sysmon_template }}.j2"
        dest: "{{ win_temp_dir }}\\{{ win_sysmon_template }}"
    - name: install sysmon with defined config
      win_command: "{{ sysmon_path }} -n -accepteula -i \"{{ win_temp_dir }}\\{{ win_sysmon_template }}\""
      register: sysmon_install
      changed_when: "'sysmon64 started.' in sysmon_install.stdout and 'The service sysmon64 is already registered.' not in sysmon_install.stdout"
      failed_when: "'Failed to validate the xml configuration' in sysmon_install.stdout"
  when: win_sysmon_template|string

- block:
    - name: install sysmon
      win_command: "{{ sysmon_path }} -i -n -accepteula"
      register: sysmon_install
      changed_when: "'sysmon64 started.' in sysmon_install.stdout and 'The service sysmon64 is already registered.' not in sysmon_install.stdout"
      failed_when: "'Failed to validate the xml configuration' in sysmon_install.stdout"
  when: not win_sysmon_template|string
